mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('production/', include('production.urls')),
    path('admin/', admin.site.urls),
]

production/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'production'
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:Product_pNames>/stock/", views.stock, name = "stock"),
    path("<str:Product_pNames>/stock/<int:ProductStocks_stockNumber>/", views.stockdetail, name = "stockdetail"),
    path("CreateAttribute/", views.CreateAttribute, name = "CreateAttribute"),
    path("createproduct/", views.createproduct, name = "createproduct"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#https://docs.djangoproject.com/en/3.0/howto/static-files/

production/models.py
from django.db import models

import datetime
# Create your models here.

class Product(models.Model): #建立產品列表
    #設定產品類別
    types = (("Plastic Lens", "塑膠鏡片"), ("機構", "機構"), ("Others", "其它"))
    #設定資料類型
    pNames = models.CharField(max_length=50, unique=True)
    pTypes = models.CharField(max_length=50, choices=types)
    pCaves = models.CharField(max_length=50)
    pModels = models.CharField(max_length=50, unique=True)
    create_time = models.DateTimeField("Create_Time:", auto_now=True)
    
    def __str__(self):
        return self.pNames


class ProductAttribute(models.Model): 
    #設定產品屬性，有很多變形可以設置。
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    attCaves = models.CharField(max_length = 5)
    pNotes = models.CharField(max_length = 200)
    attID = models.CharField(max_length=30, unique=True, blank = False, null= True)
    create_time = models.DateTimeField("Create_Time:", auto_now=True)

    def __str__(self):
        return str(self.product.pNames) + "(" + str(self.attCaves) + ")"

class ProductStocks(models.Model):
    #設定庫存
    #stockNumber = models.IntegerField(unique=True)
    stockNumber = models.CharField(max_length=50, unique=True)
    stockitem = models.ForeignKey(ProductAttribute, on_delete=models.CASCADE)
    create_time = models.DateTimeField("Create_Time:", auto_now=False, auto_now_add=True)
    #psNumbers = models.IntegerField()
    psNumbers = models.BigIntegerField()
    psNotes = models.CharField(max_length = 200)
    psChecked = models.BooleanField(default=False, help_text='是否檢驗', blank=True, null=True)
    psCheckedDate = models.DateTimeField("Check_Time:", auto_now=False, auto_now_add=False, blank=True, null = True)
    psShipped = models.BooleanField(default=False, help_text='是否出貨', blank=True, null=True)
    psShippedDate = models.DateTimeField("Check_Time:", auto_now=False, auto_now_add=False, blank=True, null = True)
    barCodeImg = models.ImageField(upload_to='uploads/', height_field=None, width_field=None, max_length=None, blank=True)
    batCodeSvg = models.TextField(null=True)

    def __str__(self):
        return self.stockitem.attID
    
class injection_mold_output(models.Model):
    imo_date = models.DateField()
    line = (("#1","GR-M02-11-1"), ("#2","GR-M02-11-2"), ("#3","GR-M02-11-3"))
    imo_line = models.CharField(max_length= 10, choices = line)
    imo_date = models.DateTimeField(auto_now=False, auto_now_add=False)    
    imo_quantity = models.IntegerField()
    #imo_responsor = 

production/forms.py
from django import forms
from production.models import Product, ProductAttribute
class CreateProductForm(forms.Form):
    #設定產品類別
    types = (("Plastic Lens", "塑膠光學鏡片"), ("Optical Lens", "光學鏡頭"), ("Others", "其它"))
    pNames = forms.CharField(max_length=50, label = "產品名稱")
    pTypes = forms.ChoiceField(choices=types, label = "產品類型")
    pCaves = forms.CharField(max_length=50, label = "產品穴數")
    pModels = forms.CharField(max_length=50, label = "產品型號")

class CreateAttributeForm(forms.Form):
    product = forms.ModelChoiceField(queryset = Product.objects.all())
    attCaves = forms.CharField(max_length = 5)
    pNotes = forms.CharField(max_length = 200)

class CreateSotckForm(forms.Form):
    stockitem = forms.ModelChoiceField(queryset = ProductAttribute.objects.all(), label = "產品名稱")
    #create_time = forms.DateTimeField(auto_now=True)
    psNumbers = forms.IntegerField(label = "包裝數量")
    psNotes = forms.CharField(max_length = 200, label = "備註")
    #psChecked = forms.BooleanField(required=False)
    #psCheckedDate = forms.DateTimeField(required=False)
    #psShipped = forms.BooleanField(required=False)
    #psShippedDate = forms.DateTimeField(required=False)

production/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from .models import Product, ProductAttribute, ProductStocks
from django.db.models import Sum
import datetime

def index(request):
    products = Product.objects.all()
    ps = [] #用來存查詢整理後的資料，再整體匯出成網頁資料。
    a = 0 #用來取得products的字典資料。

    for x in products:
        try:
            '''
            "__in" can handle querysets larger than one (multiple records of a table).
            This can be found in the django Many-to_one relationships section of the documentation. 
            https://docs.djangoproject.com/en/2.0/topics/db/examples/many_to_one/
            Django documentation can be scary for a beginner like me because of its length and depth, 
            though it provides solutions to most issues if you can crack it.
            '''
            stock = ProductStocks.objects.filter(stockitem__in = ProductAttribute.objects.filter(product_id = x.id)).aggregate(Sum('psNumbers'))
            temp = products.values()[a]
            ps.append(temp)
            a = a + 1
            temp.update(stock)
        except:
            temp = products.values()[a]
            ps.append(temp)
    #return render(request, 'production/index.html', {"products": products})
    return render(request, 'production/index.html', {"ps": ps})


#由網頁輸入到資料庫；
from production.forms import CreateProductForm, CreateAttributeForm, CreateSotckForm

def createproduct(request):
    #create = get_object_or_404(Product)
    if request.method == "POST":
        cpf = CreateProductForm(request.POST)
        if cpf.is_valid():
            Product(
                pNames = cpf.cleaned_data['pNames'],
                pTypes = cpf.cleaned_data['pTypes'],
                pCaves = cpf.cleaned_data['pCaves'],
                pModels = cpf.cleaned_data['pModels'],
                ).save()
            cpf = CreateProductForm()
    else:
        cpf = CreateProductForm()
    return render(request, 'production/createproduct.html', {"cpf": cpf})

def CreateAttribute(request):
    #product = Product.objects.get(pk = Product_id)
    #attribute = ProductAttribute.objects.filter(product = product)
    caf = CreateAttributeForm()
    if request.method == "POST":
        caf = CreateAttributeForm(request.POST)
        if caf.is_valid():
            ProductAttribute(
                product = caf.cleaned_data['product'],
                attCaves = caf.cleaned_data['attCaves'],
                pNotes = caf.cleaned_data['pNotes'],
                attID = str(caf.cleaned_data['product']) + "-" + str(caf.cleaned_data['attCaves'],)
            ).save()
        caf = CreateAttributeForm()

    return render(request, 'production/creatrpatt.html', {"caf": caf})

import barcode
from barcode.writer import ImageWriter

def batCodeSvgGenerator(stockNumber):
    EAN = barcode.get_barcode_class('ean13')
    ean = EAN(stockNumber, writer=ImageWriter())
    ean.save("media\\uploads\\" + str(stockNumber))
    return "media\\uploads\\" + str(stockNumber) + ".png"

def stock(request, Product_pNames):
    product = Product.objects.get(pNames = Product_pNames)
    attribute = ProductAttribute.objects.filter(product = product)
    att = []
    b = 0 #常數，只拿來取出數據的而己。
    for a in attribute:
        stock = ProductStocks.objects.filter(stockitem__in = ProductAttribute.objects.filter(pk = a.id)).aggregate(Sum('psNumbers'))
        #TODO: 把#1 #2的庫存總和整理到頁面去。
        temp = attribute.values()[b]
        #ps.append(temp)
        b = b + 1
        temp.update(stock)
        att.append(temp)
    csf = CreateSotckForm()
    

    if request.method == "POST":
        #將是否檢驗的checkbox核對是否勾取，並更新狀態。
        temp = ProductStocks.objects.all()
        a = request.POST
        for t in temp:
            for i in a.keys():
                if ("check" + str(t.id)) == i:
                    t.psChecked = True
                    t.psCheckedDate = datetime.datetime.now()
                    t.save()
                elif ("shipped" + str(t.id)) == i:
                    t.psShipped = True
                    t.psShippedDate = datetime.datetime.now()
                    t.save()


        #------以下是建立庫存表單分隔線
        csf = CreateSotckForm(request.POST)
        
        if csf.is_valid():
            yearmonth = datetime.datetime.now().strftime("%Y%m%d")
            numbers = str(len(ProductStocks.objects.filter(create_time__month = datetime.datetime.now().month, 
            create_time__year = datetime.datetime.now().year))).zfill(2)
            ProductStocks(
                stockNumber = yearmonth + numbers,
                stockitem = csf.cleaned_data['stockitem'],
                psNumbers = csf.cleaned_data['psNumbers'],
                psNotes = csf.cleaned_data['psNotes'],
                #psChecked = csf.cleaned_data['psChecked'],
                #psShipped = csf.cleaned_data['psShipped']
                #barCodeSvg = batCodeSvgGenerator(yearmonth + numbers)
                barCodeImg = batCodeSvgGenerator(yearmonth + numbers)
            ).save()
        csf = CreateSotckForm()
    
    
    if attribute.exists():
        stocks = ProductStocks.objects.filter(stockitem__in = attribute)
        '''
        "__in" can handle querysets larger than one (multiple records of a table).
        This can be found in the django Many-to_one relationships section of the documentation. 
        https://docs.djangoproject.com/en/2.0/topics/db/examples/many_to_one/
        Django documentation can be scary for a beginner like me because of its length and depth, 
        though it provides solutions to most issues if you can crack it.
        '''
        if stocks.exists():
            print("正常運作。")
        else:
            stocks = {}
            print("沒有庫存。")

    return  render(request, 'production/stock.html',{'att':att, 'product':product, "stocks": stocks, "csf": csf})

    #TODO:barcode programing

def stockdetail(request, Product_pNames, ProductStocks_stockNumber):
    pNames = Product_pNames
    stockNumber = ProductStocks_stockNumber
    output = ProductStocks.objects.filter(stockNumber = stockNumber)
    return render(request, 'production/stockdetail.html', {'output': output})
    

production/templates/production/createproduct.html
<h1>新建產品</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'production:createproduct' %}" method="post">
{% csrf_token %}
<label for="your_name">輸入產品訊息</label>
{{ cpf.as_p }}
<input type="submit" value="OK">
<input type="reset" value="Clear">
<input type="reset" value="Go to Index" onclick="location.href='{% url 'production:index' %}'">
</form>
<p>{{ text }}</p>

production/templates/production/creatrpatt.html
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'production:CreateAttribute' %}" method="post">
{% csrf_token %}
<label for="your_name">輸入產品訊息</label>
{{ caf.as_p }}
<input type="submit" value="OK">
<input type="reset" value="Clear">
<input type="reset" value="Go to Index" onclick="location.href='{% url 'production:index' %}'">
</form>

production/templates/production/index.html
<table class="table" border ="1">
    <thead>
        <tr>
            <th>產品ID</th>
            <th>產品類型</th>
            <th>中文品名</th>
            <th>產品型號</th>
            <th>產品穴號</th>
            <th>產品庫存</th>
        </tr>
    </thead>
    <tbody>
        {% for product in ps %}
            <tr>
                <td><a href="{% url 'production:stock' product.pNames %}">{{product.id}}</a></td>
                <td>{{product.pTypes}}</td>
                <td><a href="{% url 'production:stock' product.pNames %}">{{product.pNames}}</a></td>
                <td>{{product.pModels}}</td>
                <td>{{product.pCaves}}</td>
                <td>{{product.psNumbers__sum}}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<a href="{% url 'admin:index' %}">Production Administration</a>
<p></p>
<form action="createproduct">
    {% csrf_token %}
    <input type="submit" value="Create Product">
</form>
<form action="CreateAttribute">
    {% csrf_token %}
    <input type="submit" value="Create Attribute">
</form>

production/templates/production/stock.html
<h2>{{product.pModels}}</h2>
<form action="{% url 'production:stock' product.pNames %}" method="post">
{% csrf_token %}
{% load static %}
<table class="table" border ="1">
    <thead>
        <tr>
            <th>批號id</th>
            <th>中文品名</th>
            <th>庫存數量</th>
            <th>產品穴號</th>
            <th>建立時間</th>
            <th>是否檢驗</th>
            <th>檢驗時間</th>
            <th>是否出貨</th>
            <th>出貨時間</th>
            <th>條碼圖片</th>
        </tr>
    </thead>
    <tbody>
        {% for a in att %}
            <tr>
                <td>{{a.id}}</td>
                <td>{{product.pNames}}</td>
                <td>{{a.psNumbers__sum}}</td>
                <td>{{a.pNotes}}</td>
                <td>{{a.create_time|date:"d/m/Y H:i"}}</td>
            </tr>
            {% for s in stocks %}
            {% if s.stockitem_id == a.id %}
                <tr>
                    <td><a href="{% url 'production:stockdetail' product.pNames s.stockNumber %}">{{s.stockNumber}}</a></td>
                    <td>{{s.stockitem}}</td>
                    <td>{{s.psNumbers}}</td>
                    <td>{{s.psNotes}}</td>
                    <td>{{s.create_time|date:"d/m/Y H:i"}}</td>
                    <td>
                    {% if s.psChecked is False %}
                    {{s.psChecked}}<input type='checkbox' name="check{{s.id}}" vlaue={{s.id}}><label for={{s.id}}>檢驗完畢</label>
                    {% else %}
                    {{s.psChecked}}
                    {% endif %}
                    </td>
                    <td>{{s.psCheckedDate|date:"d/m/Y H:i"}}</td>
                    <!--
                        DJANGO的網頁時間格式！
                        https://docs.djangoproject.com/en/dev/ref/templates/builtins/#date
                    -->
                    <td>
                    {% if s.psShipped is False %}
                    {{s.psShipped}}<input type='checkbox' name="shipped{{s.id}}" vlaue={{s.id}}><label for={{s.id}}>出貨完畢</label>
                    {% else %}
                    {{s.psShipped}}
                    {% endif %}
                    </td>
                    <td>{{s.psShippedDate|date:"d/m/Y H:i"}}</td>
                    <td><img src="{{ s.barCodeImg }}" alt=""></td>
                </tr>{% endif %}
        {% endfor %}
        {% endfor %}
    </tbody>
</table>
<input type="submit" value="狀態更新">
</form>

<form action="{% url 'production:stock' product.pNames %}" method="post">
{% csrf_token %}
{{csf.as_p}}
<input type="submit" value="OK">
<input type="reset" value="Clear">
<input type="reset" value="Go to Index" onclick="location.href='{% url 'production:index' %}'"></form>

production/templates/production/stockdetail.html
{% load static %}
<body data-media-url="{% get_media_prefix %}">
{% for p in output %}
<p>stockNumber: {{p.stockNumber}}</p>
<p>stockitem: {{p.stockitem}}</p>
<p>psNumbers: {{p.psNumbers}}</p>
<p>psNotes: {{p.psNotes}}</p>
<p>psChecked: {{p.psChecked}}</p>
<p>psCheckedDate: {{p.psCheckedDate}}</p>
<p>barCodeImg: {{p.barCodeImg}}</p>
<p><img src="{{p.barCodeImg.url}}"></p>
{% endfor %}
</body>